### ISSUE TITLE
помощь нужна ?

### ISSUE THREAD

**Issue by ghost** [antowski/sonar-onec#1]

**Comment by antowski** [comment]
Пожалуй не нужна. Спасибо за предложение!  

Конкретных вопросов нет, да и отвлекать вас не хочу. Проект мягко говоря вялотекущий, надеюсь со временем руки дойдут продолжить начатое. Я знаю про плагин для bsl, разработанный в silverbulleters. Интересно было самому посмотреть как это делается,  вот сделал себе песочницу, копался потихоньку...
