### ISSUE TITLE
sonar-bsl-plugin-community

### ISSUE THREAD

**Issue by nixel2007** [antowski/sonar-onec#2]
Привет!

Приходите к нам:

https://1c-syntax.github.io/sonar-bsl-plugin-community/
https://1c-syntax.github.io/bsl-language-server/dev
https://github.com/1c-syntax/bsl-parser

и телеграм чат https://t.me/bsl_language_server

**Comment by antowski** [comment]
Привет.

Крутые вещи вы делаете, ребята. Реализация LSP для bsl очень порадовала, теперь при желании даже в VIM можно писать на 1C со всеми удобствами :). Спасибо за наводку и спасибо вообще ... за выступления на конференциях, статьи и проч. Своими действиями тАщите сообщество 1С вперед. Жму руку.

**Comment by nixel2007** [comment]
Теоритически оно даже семерку может, есть пользователи сонар-плагина, гоняющие его на семерке. но конечно не так хорошо, как восьмерку. Ждем в чате :)
